"""
Feedback Agent
==============
Generates professional recruiter-style feedback by synthesising the structured
outputs of two upstream agents:

  • Resume Analysis Agent  → resume_json  (structured candidate profile)
  • Scoring Agent          → scores_json  (scores, decision, red flags)

Responsibilities (this agent ONLY):
  - Produce actionable strengths, weaknesses, improvement suggestions,
    and top-3 priority improvements.
  - Does NOT re-parse the PDF, recalculate scores, or generate career roadmaps.

Flow:
  1. Receive both dicts from the Orchestrator.
  2. Serialise them into a combined prompt.
  3. Call Gemini via Google ADK with a strict output_schema.
  4. Validate and return a dict matching FeedbackSchema.
"""

import os
import json
import asyncio
import time
from typing import List, Optional

import nest_asyncio
from dotenv import load_dotenv
from google.genai import types
from google.adk import Agent, Runner
from google.adk.sessions import InMemorySessionService
from pydantic import BaseModel, Field

load_dotenv()


# ---------------------------------------------------------------------------
# Pydantic Schema
# ---------------------------------------------------------------------------

class FeedbackSchema(BaseModel):
    """Recruiter-style feedback synthesised from resume analysis and scoring."""

    strengths: List[str] = Field(
        ...,
        description=(
            "What the candidate has done well. "
            "Focus on concrete evidence: strong titles, relevant experience, "
            "impressive projects, certifications, high ATS score, etc."
        ),
    )
    weaknesses: List[str] = Field(
        ...,
        description=(
            "Specific gaps or problems: missing skills, vague descriptions, "
            "lack of measurable impact, poor formatting signals, missing sections. "
            "Be constructive, not harsh."
        ),
    )
    recruiter_comments: List[str] = Field(
        ...,
        description=(
            "Internal-style notes a recruiter would write when reviewing this "
            "candidate. Tone should be direct, professional, and candid."
        ),
    )
    resume_improvement_suggestions: List[str] = Field(
        ...,
        description=(
            "Actionable, specific steps the candidate can take to strengthen their resume: "
            "stronger action verbs, quantified achievements, missing keywords for ATS, "
            "section restructuring, GitHub/LinkedIn, project descriptions showing impact."
        ),
    )
    priority_improvements: List[str] = Field(
        ...,
        description=(
            "Exactly 3 improvements that would have the BIGGEST positive impact, "
            "ordered from highest to lowest impact."
        ),
    )


# ---------------------------------------------------------------------------
# Google ADK Agent definition
# ---------------------------------------------------------------------------

feedback_adk_agent = Agent(
    name="feedback_agent",
    model="gemini-2.5-flash",
    instruction="""
You are a senior technical recruiter and career advisor with 15+ years of experience
evaluating resumes and coaching candidates in the tech industry.

You have been given TWO structured JSON documents:
  1. A parsed resume profile (extracted by an AI parsing agent).
  2. A recruiter score evaluation (generated by a separate AI scoring agent).

Your task is to generate comprehensive, professional, and ACTIONABLE feedback
to help the candidate understand exactly where they stand and what to improve.
Write as if you are preparing detailed notes for a hiring committee or a career
coaching session.

FEEDBACK GENERATION INSTRUCTIONS:

1. strengths  (at least 3, up to 6 items)
   - Highlight what the candidate has genuinely done well.
   - Base every point on concrete evidence in the resume or scores.

2. weaknesses  (at least 3, up to 6 items)
   - Identify honest, specific gaps or problems.
   - Cover: missing/weak skills, vague bullets, lack of measurable results,
     employment gaps, poor formatting signals, missing sections, low category scores.
   - Reference the scoring data where relevant.

3. recruiter_comments  (3 to 5 items)
   - Write candid, internal-style notes exactly as a recruiter would log them.
   - Mention the candidate by name when appropriate.

4. resume_improvement_suggestions  (4 to 7 items)
   - Give concrete, immediately-actionable improvements.
   - Be SPECIFIC - do NOT say "improve your resume."
   - Cover: stronger action verbs, quantified achievements, missing ATS keywords,
     section restructuring, adding GitHub/LinkedIn if absent, project descriptions
     that show business impact.

5. priority_improvements  (EXACTLY 3 items)
   - Select the TOP 3 changes that would most dramatically improve this candidate's
     evaluation. Order from HIGHEST to lowest impact.
   - Each item should clearly explain WHY it is high priority.

STRICT REQUIREMENTS:
- Return ONLY valid JSON matching this exact schema (no markdown fences, no extra text):
{
  "strengths": [string, ...],
  "weaknesses": [string, ...],
  "recruiter_comments": [string, ...],
  "resume_improvement_suggestions": [string, ...],
  "priority_improvements": [string, string, string]
}
- priority_improvements must contain EXACTLY 3 items.
- All items must be complete, professional sentences.
- Do not repeat the same point across multiple fields.
    """,
    generate_content_config=types.GenerateContentConfig(
        temperature=0.3,  # Slightly warmer for natural, varied language
    ),
)


# ---------------------------------------------------------------------------
# Event-loop helper (shared pattern across all agents)
# ---------------------------------------------------------------------------

def _run_in_loop(coro):
    """Execute an async coroutine safely inside or outside a running event loop."""
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    if loop.is_running():
        nest_asyncio.apply()
        return loop.run_until_complete(coro)

    return asyncio.run(coro)


def _run_with_retry(coro_factory, max_retries: int = 3, base_delay: float = 5.0):
    """
    Run a coroutine factory with exponential backoff retry logic.
    Retries on 503 UNAVAILABLE (model overload) errors from the Gemini API.
    """
    last_exc = None
    for attempt in range(max_retries + 1):
        try:
            return _run_in_loop(coro_factory())
        except Exception as exc:
            last_exc = exc
            err_str = str(exc)
            if "503" in err_str or "UNAVAILABLE" in err_str:
                if attempt < max_retries:
                    wait = base_delay * (2 ** attempt)
                    print(f"[Retry {attempt + 1}/{max_retries}] Model overloaded (503). "
                          f"Waiting {wait:.0f}s before retry...")
                    time.sleep(wait)
                    continue
            raise
    raise last_exc


# ---------------------------------------------------------------------------
# Public entry-point
# ---------------------------------------------------------------------------

def generate_feedback(
    resume_json: dict,
    scores_json: dict,
    api_key: Optional[str] = None,
) -> dict:
    """
    Generate comprehensive recruiter-style feedback from resume profile and scoring.

    Args:
        resume_json: Output of analyze_resume_text() — structured candidate profile.
        scores_json: Output of score_candidate() — scores, decision, red flags, etc.
        api_key:     Google Gemini API Key. Falls back to GEMINI_API_KEY env var.

    Returns:
        dict matching FeedbackSchema.

    Raises:
        ValueError:   If no API key is available.
        RuntimeError: If the agent returns an empty response.
    """
    resolved_key = api_key or os.getenv("GEMINI_API_KEY")
    if not resolved_key:
        raise ValueError(
            "Google Gemini API Key is missing. "
            "Set GEMINI_API_KEY in your .env file or pass it explicitly."
        )
    os.environ["GEMINI_API_KEY"] = resolved_key

    resume_str = json.dumps(resume_json, indent=2, default=str)
    scores_str = json.dumps(scores_json, indent=2, default=str)

    async def _run():
        session_service = InMemorySessionService()
        runner = Runner(
            app_name="AI_Recruiter",
            agent=feedback_adk_agent,
            session_service=session_service,
            auto_create_session=True,
        )

        prompt_input = (
            f"CANDIDATE RESUME PROFILE (Structured JSON):\n{resume_str}\n\n"
            f"RECRUITER SCORING EVALUATION (Structured JSON):\n{scores_str}"
        )
        result_text = ""
        async for event in runner.run_async(
            user_id="recruiter_pipeline",
            session_id="session_feedback",
            new_message=types.Content(parts=[types.Part(text=prompt_input)]),
        ):
            if event.content and event.content.parts:
                result_text = event.content.parts[0].text

        if not result_text:
            raise RuntimeError("Feedback Agent returned an empty response.")

        # Strip markdown fences if the model added them anyway
        clean = result_text.strip()
        if clean.startswith("```"):
            clean = clean.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

        validated = FeedbackSchema.model_validate_json(clean)
        result = validated.model_dump()
        # Enforce the schema contract: priority_improvements must be exactly 3 items
        result["priority_improvements"] = result["priority_improvements"][:3]
        return result

    return _run_with_retry(_run)
